// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package _db

import (
	"database/sql"
)

type ExampleTable struct {
	ID        int32
	Name      sql.NullString
	Email     sql.NullString
	CreatedAt sql.NullTime
}
