// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package _db

import (
	"database/sql"
	"time"
)

type PaymentHandlerParentUser struct {
	ID           int32
	UserID       string
	ParentUserID string
	CreatedAt    sql.NullTime
	IsActive     bool
}

type PaymentHandlerTblmPaymentDetail struct {
	ID           sql.NullInt32
	Date         int64
	ReceivedFrom string
	Pan          string
	Address      string
	SumOfRupees  string
	CreatedAt    sql.NullTime
	IsActive     sql.NullBool
	UserID       sql.NullString
}

type PaymentHandlerTblmUser struct {
	ID           int32
	UserID       string
	Role         string
	CreatedAt    time.Time
	Name         string
	ParentUserID string
}
