// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package _db

import (
	"database/sql"
)

type PaymentHandlerTblmPaymentDetail struct {
	Date         int64
	ReceivedFrom string
	Pan          string
	Address      sql.NullString
	SumOfRupees  string
	CreatedAt    sql.NullTime
	IsActive     sql.NullBool
}

type PaymentHandlerTblmUser struct {
	ID        sql.NullInt32
	UserID    string
	Name      string
	Role      string
	CreatedAt sql.NullTime
}
